### ISSUE TITLE
Automatically lock issues/prs that after being closed for an extended period

### ISSUE THREAD

**Issue by josephperrott** [angular/github-robot#4]
Requirements:
* Issues and PR threads should automatically be locked after 30 days of inactivity once they are closed. 
* The bot should provide a message explaining why the issue is closed and steps to take if needed
* The bot should not close or lock threads that are currently open.

All of these requirements are covered by: https://github.com/dessant/lock-threads

I think the best option would be to use [combining apps](https://probot.github.io/docs/deployment/#combining-apps) feature of probot to use the `lock-hreads` bot alongside the angular `github-robot` to perform the current tasks as well as the auto-locking tasks.

**Comment by ocombe** [comment]
@IgorMinar @manughub are we ok with this? It should be easy to integrate with the bot

**Comment by IgorMinar** [comment]
There are several things we should very clearly consider and specify:

- closing issues:
  - we should have the robot close issues that were flagged because they were not actionable/reproducible without more input from the reporter or other community member
    - what should be the flag to indicate this?
    - what should be the timeout? I suggest two weeks...
    - the issue should be closed with clear instructions about how to reopen the issue (open a new one and refer to the old one)
  - what about closing issues that have been fixed?
    - today the issues are autoclosed by github but it's very unclear as to when the fix will be released on npm, a bot could comment on the autoclosed issue and using the tags on the PR that closed the issue let the users know if the change will be released in the next patch release or the next minor/major release (after such comment we could lock the issue)
- locking issues:
  - is there any benefit to not locking all the closed issues immediately?
    - why wait?
    - if we wait, who is going to watch the comments?

So while I do want the bot to handle this, I think we needs to think through how this stuff is actually going to work.

**Comment by jelbourn** [comment]
@IgorMinar I consider _closing_ issues to be a separate matter entirely. We can open a separate issue for that, but IMO, we should never automatically close issues.

For locking, we wait because people sometimes chime in afterwards with something like "Actually this didn't fix anything", or "This breaks this other thing". I've seen it happen enough that I wouldn't want to shut down discussion immediately. 

The main thing I want out of auto-locking old closed issues/prs is to stop getting emails from people  commenting on issues that were closed more than 6 months ago. I feel like I get at least a dozen per week.

**Comment by manughub** [comment]
@jelbourn I think auto-closing makes sense in some cases (eg: a defect was logged, its needs repro and the submitter has not provided that in x days). Its not actionable at that point. I dont see a problem with these getting auto-closed after a predefined interval has elapsed.

**Comment by IgorMinar** [comment]
@jelbourn I think the two are related because if we automatically lock all issues as I'm suggesting then we need to close issues differently.

I understand that you monitor issues you closed for new comments, but do you do that even for issues that you didn't close and were not subscribed to? I don't think we can have an expectation that all of us will monitor and follow up on all comments posted on closed issues. This is why I would rather autolock all issues and direct people to open new issues if the problem persists or if the fix broke something else.

**Comment by jelbourn** [comment]
Mainly my resistance to insta-lock is perception- it comes across as super harsh. When it happens a month later, it seems like regular project maintenance.

**Comment by IgorMinar** [comment]
My concern is that if we don't insta-lock, the perception is that we heard the feedback and didn't act on it when in fact we never saw the feedback since we almost never look at closed issues.

I'd rather be very explicit about the issue workflow and set the right expectations as well as course of action for any unresolved or newly created issues than to set wrong expectations and disappoint.

**Comment by jelbourn** [comment]
cc @stephenfluin

**Comment by filipesilva** [comment]
I'm in a similar position to @jelbourn where I get a very high volume of notifications on old issues. It was in the order of 20 per day until I started unsubscribing from them as they popped up.

I feel an issue report is heavily dependent on the context of when it was first opened and discussed. Right after it is resolved/closed, there can be follow up reports that it is not fixed, question about when the fix is available and in what version, and questions about usage. 

But after a period of time, extra comments are unlikely to be relevant. Even if a user sees the same symptoms, it's probably not the same problem and the discussion that happened before is likely not applicable to finding a solution anymore.

I think the concern that @IgorMinar brought up is a real thing:
>  if we don't insta-lock, the perception is that we heard the feedback and didn't act on it 

But insta-locking just moves the 'feedback cutoff' to whenever the caretaker ends up merging a given fix.

For example, I have an issue that I am working on. I read through it, put up a PR, then it sits there for a while until it's merged. Between the time when I last checked the comments and when the fix is merged, any number of comments might have been submitted to an open issue. After the fix is merged I can respond but users cannot. 

As an aside, GitHub does not list references in a locked issue. If issue 1 is locked, and in issue 2 I mention that it is related to issue 1, in issue one there will not be any `filipesilva referenced this issue` message. This makes it hard to see how many times a closed issue is referended.

**Comment by trotyl** [comment]
Possibly "auto close issue" make sense to new issues which doesn't fill the issue template (exclude those from team members), they're most likely bad-formed support questions can be closed by an saved reply.

**Comment by josephperrott** [comment]
Closed by https://github.com/angular/dev-infra/issues/16
